#!/bin/env bash

# list of scripts
declare -A options=(
    [" : Configs"]="rofi-configs"
    [" : Links"]="rofi-links"
    [" : Translator"]="rofi -show t -modi t:rofi-translate -theme-str 'listview{lines:0;}'"
    [" : Powermenu"]="rofi-power"
    [" : Screenshot"]="rofi-ss"
    [" : Calculator"]="rofi -show c -modi c:rofi-calc -theme-str 'listview{lines:0;}'"
    # [" : Calculator"]="rofi -show calc -modi calc -no-show-match -no-sort"
)

# creates the menu
choice=$(printf '%s\n' "${!options[@]}" |\
        rofi -dmenu -i -p '')

# runs selected script
# exits otherwise
if [ "$choice" ]; then
    eval ${options["$choice"]}
else
    echo "exit 1"; exit 1
fi
