#!/bin/env bash


declare -A links=(
    ["DuckDuckGo"]="start.duckduckgo.com"
    ["Arch Linux"]="archlinux.org"
    ["GitHub"]="github.com/login"
    ["GitLab"]="gitlab.com/"
    ["Creator"]="github.com/Kungger-git"
    ["Suckless"]="suckless.org"
    ["Gmail"]="mail.google.com/"
    ["Reddit"]="reddit.com/login"
    ["Linkedin"]="linkedin.com/login"
    ["Facebook Messenger"]="messenger.com/login"
    ["Facebook"]="facebook.com/login"
    ["YouTube"]="youtube.com"
    ["WallpaperFlare"]="wallpaperflare.com"
)

choice=$(printf '%s\n' "${!links[@]}" | rofi -dmenu -i -p '')

# opens the link using default browser..
# make sure you installed one :)
if [ "$choice" ]; then
    xdg-open "https://${links[$choice]}"
else
    echo "Exiting..."; exit 1
fi
